# Generated by Django 5.1.6 on 2025-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
