# Generated by Django 5.1.6 on 2025-04-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_models', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_models.project'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='talent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_models.talent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
