# Generated by Django 5.1.6 on 2025-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_models', '0005_alter_contract_project_id_alter_contract_talent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent_dsc',
            name='prof',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
